#!/usr/bin/env python3
"""Editorial reader-navigation metadata for the Gospel of Truth.

These headings and paragraph groupings are transparent reader aids only. They
are not source-authoritative verses and must be rendered outside translation.text.
"""
from __future__ import annotations

from typing import Any

READER_NAVIGATION_NOTE = (
    'Section break and heading are editorial reader-navigation aids only; '
    'they are not source-authoritative verse divisions and do not alter translation.text.'
)

# Paragraph numbers are 1-based within each section's translation.text, split on
# blank lines. Titles are editorial navigation labels, not translated wording.
READER_SECTIONS: dict[str, list[dict[str, Any]]] = {'001': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Gospel as Joy and Revelation'}],
 '002': [{'paragraph_end': 1, 'paragraph_start': 1, 'section': 1, 'title': 'Searching in the Fog'},
         {'paragraph_end': 2, 'paragraph_start': 2, 'section': 2, 'title': 'Error Without a Root'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Works of Forgetfulness'},
         {'paragraph_end': 4,
          'paragraph_start': 4,
          'section': 4,
          'title': 'Knowledge Dissolves Forgetfulness'}],
 '003': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Father Keeps the All'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'The Living Book Revealed'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Jesus Publishes the Decree'},
         {'paragraph_end': 4,
          'paragraph_start': 4,
          'section': 4,
          'title': 'Teaching Through Death and Life'}],
 '004': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'Names in the Book of the Living'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'Hearing the One Who Calls'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Prepared in Thought and Will'},
         {'paragraph_end': 4,
          'paragraph_start': 4,
          'section': 4,
          'title': 'Called by Name at the End'},
         {'paragraph_end': 5,
          'paragraph_start': 5,
          'section': 5,
          'title': 'Knowledge, Return, and Rest'},
         {'paragraph_end': 6,
          'paragraph_start': 6,
          'section': 6,
          'title': 'Brought Back from Error'},
         {'paragraph_end': 7, 'paragraph_start': 7, 'section': 7, 'title': 'Letters of the Truth'}],
 '005': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'Jesus of Infinite Sweetness'},
         {'paragraph_end': 2, 'paragraph_start': 2, 'section': 2, 'title': 'The Bosom Made Known'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Deficiency Dissolved by Completion'},
         {'paragraph_end': 4,
          'paragraph_start': 4,
          'section': 4,
          'title': 'From Multiplicity into Unity'}],
 '006': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Word Among the Jars'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'Error Finds Itself Empty'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Truth Joins Them to the Father'}],
 '007': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'Receiving Form and Name'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'What Has Not Yet Appeared'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Root and Fruit in the Father'}],
 '008': [{'paragraph_end': 1, 'paragraph_start': 1, 'section': 1, 'title': 'Shadows of the Night'},
         {'paragraph_end': 3,
          'paragraph_start': 2,
          'section': 2,
          'title': 'Terror Dissolved by Light'},
         {'paragraph_end': 5,
          'paragraph_start': 4,
          'section': 3,
          'title': 'Awakening from Ignorance'},
         {'paragraph_end': 6,
          'paragraph_start': 6,
          'section': 4,
          'title': 'The Spirit Raises the Fallen'}],
 '009': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Son Reveals the Father'},
         {'paragraph_end': 2, 'paragraph_start': 2, 'section': 2, 'title': 'The Light Speaks Life'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Knowledge Ends Captivity'},
         {'paragraph_end': 9,
          'paragraph_start': 4,
          'section': 4,
          'title': 'Way, Knowledge, Discovery, Strength, Purity'}],
 '010': [{'paragraph_end': 1, 'paragraph_start': 1, 'section': 1, 'title': 'The One Sheep Found'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'Sabbath, Salvation, and the Perfect Day'}],
 '011': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'Strengthen Those Who Stumble'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'Do Not Return to What Was Cast Off'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'The Father’s Fragrance and Warmth'}],
 '012': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Good News of Fullness'},
         {'paragraph_end': 2, 'paragraph_start': 2, 'section': 2, 'title': 'Grace Fills the Need'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'Chrism, Mercy, and Paradise'}],
 '013': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Good in the Father’s Thought'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'The Logos Manifests the Words'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'The Father’s Will and Return'}],
 '014': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'The Invisible Name Revealed in the Son'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'The Name Belongs to the Father'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 3,
          'title': 'The Proper Name, Not Borrowed'},
         {'paragraph_end': 4,
          'paragraph_start': 4,
          'section': 4,
          'title': 'The Beloved Name from the Depth'}],
 '015': [{'paragraph_end': 2,
          'paragraph_start': 1,
          'section': 1,
          'title': 'Not Revealed in Harshness'},
         {'paragraph_end': 3,
          'paragraph_start': 3,
          'section': 2,
          'title': 'Rest in the Complete One'}],
 '016': [{'paragraph_end': 1,
          'paragraph_start': 1,
          'section': 1,
          'title': 'Coming to the Place of Rest'},
         {'paragraph_end': 2,
          'paragraph_start': 2,
          'section': 2,
          'title': 'Children Filled with the Father’s Seed'},
         {'paragraph_end': 3, 'paragraph_start': 3, 'section': 3, 'title': 'Manuscript Lacuna'},
         {'paragraph_end': 4,
          'paragraph_start': 4,
          'section': 4,
          'title': 'The Holy Thought Remains'}]}


def reader_navigation_for_section(section_id: str, heading: str) -> dict[str, Any]:
    nav: dict[str, Any] = {
        'division_kind': 'editorial_section',
        'order': int(section_id),
        'heading': heading,
        'authoritative_division': False,
        'note': READER_NAVIGATION_NOTE,
    }
    reader_sections = READER_SECTIONS.get(section_id)
    if reader_sections:
        nav['reader_sections'] = [dict(section) for section in reader_sections]
    return nav
